version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: prajwalgpt-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../.env
    environment:
      API_PORT: ${API_PORT:-8000}
      OLLAMA_HOST: http://ollama:11434
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ../shared:/app/shared:ro
      - ../storage:/app/storage
    depends_on:
      - ollama

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../.env
    environment:
      VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - api

volumes:
  ollama_data:
