version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../.env
    environment:
      API_PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ../shared:/app/shared:ro
      - ../storage:/app/storage

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../.env
    environment:
      VITE_API_BASE_URL: ${API_BASE_URL:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - api
